development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  database: 1337demos_development
  username: '1337demos'
  password: '1337demos'

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
  database: 1337demos_test
  username: '1337demos'
  password: '1337demos'


cucumber:
  <<: *test